name: Deploy 

on: 
  push:
    - main 


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with: 
          python-version: 3.x

      - name: Install dependencies
        run: |
          pipenv install
          pipenv shell
          pip install Flask

      - name: Deploy
        run: |
          heroku login -i
          